config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,:controllers=>{registrations:"registrations"}
  resources :tweets
  root to: "tweets#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  validates :body , presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
      
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def after_sign_up_path_for(resource)
      root_path(resource)
    end
    def after_inactive_sign_up_path_for(resource)
        root_path(resource)
    end
   
    private 
    def sign_up_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end

    def sign_update_params
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end

    def account_update_params 
        params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
     
  end
  

app/controllers/tweet_controller.rb
class TweetController < ApplicationController
    def index
        @tweet=Tweet.all
    end
    
    def new

    end
    
    def edit

    end
    
    def create

    end
    
    def destroy
        
    end
   

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :set_tweet, only: [:show , :edit , :update, :destroy]
     before_action :authenticate_user! ,except: [:index, :show]
    def index
        @tweets=Tweet.all.order("created_at DESC")
        @tweet=Tweet.new()

    end
    
     
    def show
        @tweet = Tweet.find(params[:id])
   end

   def new
         @tweet=current_user.tweets.build
   end

   def create
    p "-------------------------------"
    p tweet_params
    @tweet = current_user.tweets.build(tweet_params)
#     @tweet.user_id=1
         if @tweet.save
         redirect_to root_path
         else
         render :new, status: :unprocessable_entity
         end
    end

    def edit
         @tweet=Tweet.find(params[:id])
    end

    def update
         @tweet = Tweet.find(params[:id])
         puts params
         puts"-------------------------------"
         if @tweet.update(tweet_params)
           redirect_to tweet_url(params[:id])
         else
           render :edit, status: :unprocessable_entity
         end
    end  

    def destroy
         @tweet = Tweet.find(params[:id])
         @tweet.destroy
         redirect_to root_path, status: :see_other
    end
         
    

    def set_tweet
     @tweet= Tweet.find(params[:id])
    end


    private
    def tweet_params  
        p"========================"
         params.require(:tweet).permit(:body)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/b492b7fc6e.js
" crossorigin="anonymous"></script>
     <%=stylesheet_link_tag "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/fontawesome.min.css
"%>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
       <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awsome.min.css" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice]%>
      <div class="notification is-primary global-notification">
       <p class="notice"><%=notice %></p>

      </div>
    <%end%>
    <%if flash[:alert]%>
      <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>

      </div>
    <%end%>

      <nav class="navbar is-info">
        <div class="navbar-brand">
          <%=link_to root_path, class: "navbar-item" do%>
          <h1 class="title is-5">Twitter</h1>      
          <%end%>
        
          <div class="navbar-burger burger" data-target="navbarExample">
            <span></span>
            <span></span>
            <span></span>
            </div>
        </div>

        <div id="navbarExample" class="navbar-menu">
          <div class="navbar-end">
            <div class ="field is-grouped">
            <p class="control">
              <%=link_to "new Tweet",new_tweet_path , class: "button is_info is-inverted"%>
            </p>

            <% if user_signed_in? %>
            <p class="control">
              <%= link_to current_user.name ,edit_user_registration_path, class: "buttom is-info is-inverted"%>
            </p>
            
            <%= link_to "Logout", destroy_user_session_path,data: { 'turbo-method': :delete, 'turbo-confirm': 'Are you sure want to signout?'},
                             class: "button is-info"%>
            </p>
            <%else%>

            <p class="control">
              <%=notice%>
              <%= link_to "Sign In" , new_user_session_path,class:"button  is-info"%>

              </p>

            <p class="control">
              <%= link_to "Sign Up" , new_user_registration_path ,class:"button  is-info"%>
              </p>
              <%end%>
             
            <%# <%=link_to "sign_out", destroy_user_session_path%> 
           
            </div>
          </div>
        </div>
      </nav>


      <%= yield %>
  </body>
</html>

app/views/tweet/_feed.html.erb
<div class="column is-half">
    <article class="media box">
    <figure class="media-left">
        <p class="image is-64x64">
            <img src="https://bulma.io/images/placeholders/64x64.png">
        </p>
    </figure>
    <div class="media-content">
    </div>
    </article>

</div>

<%@tweet.each do |t|%>
<div class="box">
    <article class="media">
        <div class="media-left">
            <figure class="image is-64x64">
                  <img src="https://bulma.io/images/placeholders/64x64.png">
            </figure>
        </div>


        <div class="media-content">
            <div class="content">
                <strong>Shekhar</strong><br/>
                <small>@itsshekhar</small><br/>
                <p><%=t.body%></p>
            </div>


            <nav class="level">
                <div class="level-left is-mobile">
                    <%= link_to t ,class: "level-item" do%>
                        <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                    <%end%>
                   
                    <%=link_to edit_tweet_path(t), class: "level-item" do%>
                        <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                    <%end%>
                    
                     <%=link_to tweet_path(t) ,method: :delete,data: {confirm:"are your sure want to delete this tweet?"} do %>
                            <span class="icon"><i class="fa fa-trash" aria-hidden="true"></i></span>
                    <%end%>

                </div>
            </nav>
        </div>
    </article>
<div>
<%end%>

app/views/tweet/_who-to-follow.html.erb
<div class="column">
    <nav class="panel">
        <p class="panel-heading">Who to follow</p>
    </nav>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>Shivam</strong>
                    <small>@shivamyadav</small>
                </p>
            </div>
        </div>
        </article>        
    </div>



    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>sury</strong>
                    <small>@suryasingh</small>
                </p>
            </div>
        </div>
        </article>        
    </div>

    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>shwetank</strong>
                    <small>@shwetank_rockey</small>
                </p>
            </div>
        </div>
        </article>        
    </div>


</div>

app/views/tweet/index.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
            <%=render 'feed' %>
            
        </div>
        
    </div>
    <%=render 'who-to-follow'%>
</section>

app/views/tweets/_feed.html.erb
<div class="column is-half">
<%if user_signed_in?%>
    <article class="media box">
    <figure class="media-left">
        <p class="image is-64x64">
            <%gravatar_image_tag(current_user.email,size: 64,alt: current_user.name)%>
        </p>
    </figure>

    <div class="media-content">
    
    <%= render 'tweets/form'%>
  
    </div>
    </article>

  <%end%>

<div class="box">

<%@tweets.each do |t|%>

    <article class="media">
        <div class="media-left">
            <figure class="image is-64x64">
                  <img src="https://bulma.io/images/placeholders/64x64.png">
            </figure>
        </div>


        <div class="media-content">
            <div class="content">
                <strong><%=t.user.name%></strong><br/>
                <small><%=t.user.username%></small><br/>
                <p><%=t.body%></p>
            </div>

            <% if user_signed_in?%>     
            <% if t.user.id==current_user.id%>
          
            <nav class="level">
                <div class="level-left is-mobile">
                <span class="button"><i class="fa fa-heart" aria-hidden="true"></i></span>
                    <%= link_to t ,class: "level-item" do%>
                        <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                    <%end%>
                   
                    <%=link_to  edit_tweet_path(t), class: "level-item" do%>
                        <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                    <%end%>
                    
                     <%=link_to tweet_path(t) ,method: :delete,data: {confirm:"are your sure want to delete this tweet?"} do %>
                            <span class="icon"><i class="fa fa-trash" aria-hidden="true"></i></span>
                    <%end%>

                </div>
            </nav>
            <%end%>
            <%end%>
        </div>
    </article>
    <%end%>
</div>
</div>

app/views/tweets/_form.html.erb
<%= simple_form_for @tweet do |f|%>
<%=f.error_notification %>
<div class="field">
    <div class="control">
        <%=f.input :body, label:"Tweet", input_html: {class: "textarea"}, wrapper: false , label_html: 
        {class: "label"}, placeholder: "Compose a new tweet..." %>
        
    </div>
</div>
<%= f.button :submit, class:  "button is-info"%>
<%end%>

app/views/tweets/_profile.html.erb
<div class="column is-one-quarter">
    <nav class="panel">
        <p class="panel-heading">Profile</p>
            <div class="panel-block">
                <article class="media">
                    <div class="media-left">
                        <figure class="image is-64x64">
                             <%=gravatar_image_tag(current_user.email,size: 64,alt: current_user.name)%>
        
                        </figure>
                    </div>

                    <div class="media-content">
                        <div class="content">
                            <p>
                                <strong><%= current_user.name%></strong>
                                <small><%=current_user.username %></small>
                            </p>
                        </div>
                    </div>

                </article>
            </div>
            <div class="panel-block">
                <div class="level is-mobile">
                    <div class="level-item has-centered-text">
                    <div>
                        <p class="heading">Tweets</p>
                        <p class="title is-6"> <%= current_user.tweets.count%></p>
                        </div> 
                    </div>
                </div>

                <div class="level is-mobile">
                    <div class="level-item has-centered-text">
                    <div>
                        <p class="heading"> FOLLOWINGS</p>
                        <p class="title is-6"> <%= current_user.tweets.count%></p>
                        </div> 
                    </div>
                </div>

                <div class="level is-mobile">
                    <div class="level-item has-centered-text">
                    <div>
                        <p class="heading"> FOLLOWERS</p>
                        <p class="title is-6"> <%= current_user.tweets.count%></p>
                        </div> 
                    </div>
                </div>
                
            </div>
        
    </nav>
</div>

app/views/tweets/_trends.html.erb
<div class="column is-one-quarter">
    <nav class="panel">


    
        <p class="panel-heading">Trends</p>
        
        <a class="panel-block">
        Trend 1
        </a>

        <a class="panel-block">
        Trend 2
        </a>
        
      
        
        <a class="panel-block">
        Trend 3
        </a>
        
        <a class="panel-block">
        Trend 4
        </a>
        
        <a class="panel-block">
        Trend 5
        </a>
    
    </nav>
</div>

app/views/tweets/_who-to-follow.html.erb
<div class="column">
    <nav class="panel-right">
        <p class="panel-heading">Who to follow</p>
    </nav>
    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>Shivam</strong>
                    <small>@shivamyadav</small>
                </p>
            </div>
        </div>
        </article>        
    </div>



    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>sury</strong>
                    <small>@suryasingh</small>
                </p>
            </div>
        </div>
        </article>        
    </div>

    <div class="panel-block">
        <article class="media">
            <div class="media-left">
                <figure class="image is-32x32">
                    <img src="https://bulma.io/images/placeholders/64x64.png">
                </figure>
            </div>
        <div class="media-content">
            <div class="content">
                <p>
                    <strong>shwetank</strong>
                    <small>@shwetank_rockey</small>
                </p>
            </div>
        </div>
        </article>        
    </div>

</div>

app/views/tweets/edit.html.erb
<h1><b>Editing </b></h1>
<%= form_with(model: @tweet) do |form| %>
 

<%= render "form" %>  

<% end %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<section class="section">
    <div class="container">
        <div class="columns">
        <% if user_signed_in? %>
        <%=render 'profile'%>
        <%else%>
            <%=render 'trends'%>
        <%end%>
            <%=render 'feed' %>
        
            <%=render 'who-to-follow'%>
        </div>     
    </div>
</section>

app/views/tweets/new.html.erb
<h1><b>Create New </b></h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"> <%=notice %></p>

<p><%=@tweet.body%></p>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>